package bind

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"mynginx/internal/util"
)

func (p *Provider) writeIncludeFile() error {
	zones, err := p.zoneNames()
	if err != nil {
		return err
	}
	sort.Strings(zones)

	var b strings.Builder
	b.WriteString("// generated by NGM. DO NOT EDIT.\n")
	for _, zone := range zones {
		zoneFile := p.zonePath(zone)
		b.WriteString(fmt.Sprintf("zone \"%s\" IN {\n", zone))
		b.WriteString("    type master;\n")
		b.WriteString(fmt.Sprintf("    file \"%s\";\n", zoneFile))
		b.WriteString("};\n\n")
	}
	return util.WriteFileAtomic(p.cfg.Bind.NamedConfInclude, []byte(b.String()), 0644)
}

func (p *Provider) zoneNames() ([]string, error) {
	ents, err := os.ReadDir(p.cfg.Bind.ZonesDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read zones dir: %w", err)
	}
	var out []string
	for _, e := range ents {
		if e.IsDir() {
			continue
		}
		n := e.Name()
		if !strings.HasSuffix(n, p.cfg.Bind.ZoneFileSuffix) {
			continue
		}
		out = append(out, strings.TrimSuffix(n, p.cfg.Bind.ZoneFileSuffix))
	}
	return out, nil
}
