api:
  listen: "0.0.0.0:9601"
  hostname: ""
  tokens:
    - "change-me-please"
  allow_ips:
    - "127.0.0.1/32"
    - "10.0.0.0/8"
    - "2.85.0.0/16"

nginx:
  root: "/etc/nginx/"
  main_conf: "nginx.conf"
  sites_dir: "conf/sites"
  bin: "/usr/sbin/nginx"
  service_name: "nginx"
  cache_root: "/var/cache/nginx"

  # keep user nginx, but you want runtime group alignment with nobody
  user: "nginx"
  group: "nobody"

  apply:
    staging_dir: "conf/.staging"
    backup_dir: "conf/.backup"
    test_before_reload: true
    reload_mode: "signal"

certs:
  mode: "certbot"
  email: "admin@myipnetworks.com"
  webroot: "/var/www/html"
  letsencrypt_live: "/etc/letsencrypt/live"
  certbot_bin: "certbot"

phpfpm:
  default_version: "8.3"
  versions:
    "8.3":
      pools_dir: "/etc/opt/remi/php83/php-fpm.d"
      service: "php83-php-fpm"
      sock_dir: "/var/opt/remi/php83/run/php-fpm"

hosting:
  home_root: "/home"
  sites_root_name: "sites"

  # this must match the group nginx uses to traverse/read site files
  web_group: "nobody"

security:
  audit_log: "/var/log/ngm/audit.log"

storage:
  driver: "sqlite"
  dsn: "/var/lib/ngm/ngm.db"
  sqlite_path: "/var/lib/ngm/ngm.db"

dns:
  enabled: false
  provider: "bind"
  default_template: "default"
  default_ipv4: "84.54.49.31"
  default_ipv6: ""

  bind:
    named_conf_include: "/etc/named/ngm-zones.conf"
    zones_dir: "/var/named/ngm"
    rndc_bin: "rndc"
    checkconf_bin: "named-checkconf"
    checkzone_bin: "named-checkzone"
    named_conf_path: "/etc/named.conf"
    zone_file_suffix: ".zone"

  templates:
    default:
      ttl: 3600
      soa:
        mname: "ns1.example.net."
        rname: "hostmaster.example.net."
        refresh: 3600
        retry: 900
        expire: 1209600
        minimum: 3600
      nameservers:
        - "ns1.example.net."
        - "ns2.example.net."
      records:
        - name: "www"
          type: "CNAME"
          value: "@"
          ttl: 3600
